name: 'kubernetes-canary-action'
description: 'An action to handle kubectl output parsing for canary deploys and rollbacks'
author: 'Smartly.io'
inputs: {}
runs:
  using: 'node12'
  main: 'dist/index.js'
