name: Build

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version-file: .node-version
    - name: "Install"
      run: |
        npm install
    - name: "Prettier"
      run: |
        npm run format-check
    - name: "Lint"
      run: |
        npm run lint
    - name: "Test"
      run: |
        npm run test
    - name: "build"
      run: |
        npm run build
        npm run package

  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v6
      with:
        node-version-file: .node-version
    - name: "Build action for test"
      run: |
        npm install
        npm run all
        git clean -fXd
    - name: Mock the kubectl binary
      run: |
        echo "$(pwd)/__tests__/bin" >> "$GITHUB_PATH"
    - name: Check if deployment is locked
      uses: ./
      with:
        serviceName: test-service
        kubernetesContext: test-context
        command: isLocked
    - name: Unlock deployments
      uses: ./
      with:
        serviceName: test-service
        kubernetesContext: test-context
        command: unlock
    - name: Lock deployments
      uses: ./
      with:
        serviceName: test-service
        kubernetesContext: test-context
        command: lock
        user: github-actions

  release:
    runs-on: ubuntu-24.04
    name: "Build and release action"
    needs: [build, test]
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: true
      - name: Configure git
        uses: smartlyio/github-actions@git-init-userinfo-v1
      - name: Release flow
        uses: smartlyio/github-actions@release-action-node-v1
        with:
          dry_run: ${{ github.event_name == 'pull_request' }}
          token: "${{ secrets.GITHUB_TOKEN }}"
